INSERT INTO stories (title, genre, description, body) VALUES ('Calypso', 'Humor', 'If youve ever laughed your way through David Sedariss cheerfully misanthropic stories, you might think you know what youre getting with Calypso. Youd be wrong.', "When he buys a beach house on the Carolina coast, Sedaris envisions long, relaxing vacations spent playing board games and lounging in the sun with those he loves most. And life at the Sea Section, as he names the vacation home, is exactly as idyllic as he imagined, except for one tiny, vexing realization: it's impossible to take a vacation from yourself. With Calypso, Sedaris sets his formidable powers of observation toward middle age and mortality. Make no mistake: these stories are very, very funny - it's a book that can make you laugh 'til you snort, the way only family can. Sedaris's powers of observation have never been sharper, and his ability to shock readers into laughter unparalleled. But much of the comedy here is born out of that vertiginous moment when your own body betrays you and you realize that the story of your life is made up of more past than future.This is beach reading for people who detest beaches, required reading for those who loathe small talk and love a good tumor joke. Calypso is simultaneously Sedaris's darkest and warmest book yet - and it just might be his very best.");

INSERT INTO stories (title, genre, description, body) VALUES ('The Outsider', 'Mystery', "An unspeakable crime. A confounding investigation. At a time when the King brand has never been stronger, he has delivered one of his most unsettling and compulsively listenable stories. ", "An 11-year-old boy's violated corpse is found in a town park. Eyewitnesses and fingerprints point unmistakably to one of Flint City's most popular citizens. He is Terry Maitland, Little League coach, English teacher, husband, and father of two girls. Detective Ralph Anderson, whose son Maitland once coached, orders a quick and very public arrest. Maitland has an alibi, but Anderson and the district attorney soon add DNA evidence to go with the fingerprints and witnesses. Their case seems ironclad. As the investigation expands and horrifying answers begin to emerge, King's propulsive story kicks into high gear, generating strong tension and almost unbearable suspense. Terry Maitland seems like a nice guy, but is he wearing another face? When the answer comes, it will shock you as only Stephen King can.");

INSERT INTO stories (title, genre, description, body) VALUES ('Vacationland', 'Romance', "John Hodgman - New York Times best-selling author, semifamous personality, deranged millionaire, increasingly elderly husband, father, and human of Earth - has written a memoir about his cursed travels through two wildernesses: from the woods of his home in Massachusetts, birthplace of rage, to his exile on the coast of Maine, so-called Vacationland, home to the most painful beaches on Earth.", "Vacationland is also about Hodgman's wandering in the metaphoric wilderness of his 40s, those years when dudes especially must painfully stop pretending to be the children of bright potential they were and settle into the failing bodies of the wiser, weirder dads that they are.Other subjects covered include the horror of freshwater clams, the evolutionary purpose of the mustache, which animals to keep as pets and which to kill with traps and poison, and advice on how to react when the people of coastal Maine try to sacrifice you to their strange god.After three best-selling books of fake facts, Hodgman is finally ready to tell the truth - in the same outlandish, audacious, and inimitable style that has won him fans in every medium he has worked: books, stage, social media, television, and movies.");

INSERT INTO stories (title, genre, description, body) VALUES ('Dimension of Miracles', 'Sci-Fi', "Award-winning author, narrator, and screenwriter Neil Gaiman personally selected this book, and, using the tools of the Audiobook Creation Exchange (ACX), produced this work for his audiobook label, Neil Gaiman Presents.", "In its style of humor—and even in some of the jokes—Dimension of Miracles is very obviously a precursor of Douglas Adams' Hitchhiker's Guide to the Galaxy. Douglas actually hadn't read Dimension of Miracles until very shortly after Hitchhiker came out, when people pointed him to it, and he told me that he found the experience almost shocking—it was like reading himself. He was a huge admirer of Bob Sheckley and a huge admirer of this book, and in later life, I had the privilege of introducing both of them.

Now the challenge for me with a book this funny, this strange, this perceptive was to try and find a narrator who was as iconic, somebody who could deliver the goods, somebody who could give you a book like this as it deserved to be given. And the first, and the last, and actually the only person to come to mind was John Hodgman. So I asked John, and he said yes! And he did it; he pulled it off. Listening to John—not just the suave, sensible, sane narrator of this book, but all the peculiar accents and incarnations that he is forced to adopt through here—he does it delightfully, he does it brilliantly, he's really, really funny. And so is this book. Enjoy your journey through a Dimension of Miracles.

Dimension of Miracles is a satirical science fiction novel first published by Dell in 1968. It's about Tom Carmody, a New Yorker who, thanks to a computer error, wins the main prize in the Intergalactic Sweepstakes. Tom claims his prize before the error is discovered and is allowed to keep it. However, since Tom is a human from Earth without galactic status and no space traveling experience, he has no homing instinct that can guide him back to Earth once his odyssey begins - and the galactic lottery organizers cannot transport him home. Meanwhile, his removal from Earth has caused a predatory entity to spring into existence - one that pursues and aims to destroy him. Carmody is on the run, and he ends up transporting from Earth to Earth - different phases and realities of the planet, which of course is not the time or condition he expects.");

INSERT INTO stories (title, genre, description, body) VALUES ('Me Talk Pretty One Day', 'Humor', "David Sedaris' new collection of essays - including live recordings! - tells a most unconventional life story.", "It begins with a North Carolina childhood filled with speech-therapy classes (There was the lisp, of course, but more troubling than that was my voice itself, with its excitable tone and high, girlish pitch) and unwanted guitar lessons taught by a midget. From budding performance artist (The only crimp in my plan was that I seemed to have no talent whatsoever) to clearly unqualified writing teacher in Chicago, Sedaris' career leads him to New York City and eventually, of all places, France. His move to Paris poses a number of challenges, chief among them his inability to speak the language. Arriving a spooky man-child capable of communicating only through nouns, he undertakes language instruction that leads him ever deeper into cultural confusion. Whether describing the Easter bunny to puzzled classmates or watching a group of men play soccer with a cow, Sedaris brings a view and a voice like no other to every unforgettable encounter.");

INSERT INTO stories (title, genre, description, body) VALUES ('Everything I Never Told You', 'Mystery', 'A haunting debut novel about a mixed-race family living in 1970s Ohio and the tragedy that will either be their undoing or their salvation.', "So begins the story in this exquisite debut novel about a Chinese American family living in a small town in 1970s Ohio. Lydia is the favorite child of Marilyn and James Lee; their middle daughter, a girl who inherited her mother's bright blue eyes and her father's jet-black hair. Her parents are determined that Lydia will fulfill the dreams they were unable to pursue - in Marilyn's case that her daughter become a doctor rather than a homemaker, in James' case that Lydia be popular at school, a girl with a busy social life and the center of every party.

When Lydia's body is found in the local lake, the delicate balancing act that has been keeping the Lee family together tumbles into chaos, forcing them to confront the long-kept secrets that have been slowly pulling them apart. James, consumed by guilt, sets out on a reckless path that may destroy his marriage. Marilyn, devastated and vengeful, is determined to find a responsible party, no matter what the cost. Lydia's older brother, Nathan, is certain the neighborhood bad boy Jack is somehow involved. But it's the youngest of the family, Hannah, who observes far more than anyone realizes - and who may be the only one who knows the truth about what happened.

A profoundly moving story of family, history, and the meaning of home, Everything I Never Told You is both a gripping pause-resister and a sensitive family portrait, exploring the divisions between cultures and the rifts within a family and uncovering the ways in which mothers and daughters, fathers and sons, and husbands and wives struggle, all their lives, to understand one another.");

INSERT INTO stories (title, genre, description, body) VALUES ('Sweet Tea and Sympathy', 'Romance', 'Beloved author Molly Harper launches a brand-new contemporary romance series, Southern Eclectic, with this story of a big-city party planner who finds true love in a small Georgia town.', "Nestled on the shore of Lake Sackett, Georgia, is the McCready Family Funeral Home and Bait Shop. (What, you have a problem with one-stop shopping?) Two McCready brothers started two separate businesses in the same building back in 1928, and now it's become one big family affair. And, true to form in small Southern towns, family business becomes everybody's business.

Margot Cary has spent her life immersed in everything Lake Sackett is not. As an elite event planner, Margot's rubbed elbows with the cream of Chicago society and made elegance and glamour her business. She's riding high until one event goes tragically, spectacularly wrong. Now she's blackballed by the gala set and in dire need of a fresh start - and apparently the McCreadys are in need of an event planner with a tarnished reputation.

As Margot finds her footing in a town where everybody knows not only your name but what you had for dinner last Saturday night and what you'll wear to church on Sunday morning, she grudgingly has to admit that there are some things Lake Sackett does better than Chicago - including the dating prospects.

Elementary school principal Kyle Archer is a fellow fish out of water who volunteers to show Margot the picture-postcard side of Southern living. The two of them hit it off, but not everybody is happy to see an outsider snapping up one of the town's most eligible gentleman. Will Margot reel in her handsome fish, or will she have to release her latest catch?

");

INSERT INTO stories (title, genre, description, body) VALUES ('Year Zero', 'Sci-Fi', 'An alien advance party was suddenly nosing around my planet. Worse, they were lawyering up....', "In the hilarious tradition of The Hitchhiker's Guide to the Galaxy, Rob Reid takes you on a headlong journey through the outer reaches of the universe - and the inner workings of our absurdly dysfunctional music industry.

Low-level entertainment lawyer Nick Carter thinks it's a prank, not an alien encounter, when a redheaded mullah and a curvaceous nun show up at his office. But Frampton and Carly are highly advanced (if bumbling) extraterrestrials. And boy, do they have news.

The entire cosmos, they tell him, has been hopelessly hooked on humanity's music ever since Year Zero (1977 to us), when American pop songs first reached alien ears. This addiction has driven a vast intergalactic society to commit the biggest copyright violation since the Big Bang. The resulting fines and penalties have bankrupted the whole universe. We humans suddenly own everything - and the aliens are not amused.

Nick Carter has just been tapped to clean up this mess before things get ugly, and he's an unlikely galaxy-hopping hero: He's scared of heights. He's also about to be fired. And he happens to have the same name as a Backstreet Boy. But he does know a thing or two about copyright law. And he's packing a couple of other pencil-pushing superpowers that could come in handy.

Soon he's on the run from a sinister parrot and a highly combustible vacuum cleaner. With Carly and Frampton as his guides, Nick now has 48 hours to save humanity, while hopefully wowing the hot girl who lives down the hall from him.");